name = "habit-tracker"
main = "server/index.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "dist/habit-tracker/browser"
binding = "ASSETS"

[build]
command = "npm run build"

# Expected terminal output on `npm run dev`:
# ...
# Ready on http://localhost:8787

[[d1_databases]]
binding = "DB"
database_name = "habit-tracker-db"
database_id = "e30cc489-20bc-4234-8ae7-d2b088111c26"

[vars]
ALLOWED_ORIGIN = "*"
JWT_SECRET = "super-secret-local-dev-key-1234567890"
